version: '3'
services:
  paw:
    build:
      context: .
      dockerfile: Dockerfile-paw
    ports:
     - "8081:8080"
    volumes:
     - ./data-config:/data/config
    environment:
     - CONFIGURATION_FILE_PATH=/data/config/configuration.yaml
  whisker:
    build:
      context: .
      dockerfile: Dockerfile-whisker
    ports:
      - "8082:8080"
    volumes:
      - ./data-config:/data/config
    environment:
     - CONFIGURATION_FILE_PATH=/data/config/configuration.yaml
     - CONFIGURATION_WHISKER_GIT_FOLDER=/tmp/felicette
  jenkins:
    build: vendor/jenkins
    ports:
     - "8080:8080"
    depends_on:
      - "paw"
      - "whisker"
  nginx:
    build: vendor/nginx
    ports:
     - "81:80"
  redis:
    image: "redis:alpine"
    ports:
    - "6379"
