version: '3'
services:
  paw:
    build:
      context: .
      dockerfile: Dockerfile-paw
    ports:
     - "8081:8080"
    volumes:
     - ./data-config:/data/config
  whisker:
    build:
      context: .
      dockerfile: Dockerfile-whisker
    ports:
      - "8082:8080"
    volumes:
      - ./data-config:/data/config
  jenkins:
    build: vendor/jenkins
    ports:
     - "8080:8080"
  nginx:
    build: vendor/nginx
    ports:
     - "80:80"
  redis:
    image: "redis:alpine"
    ports:
    - "6379"
