providers:
  - provider: aws
    name: default
    credentials:
      access_key: MY_ACCESS_KEY # if you do not specify, it will use iam role
      secret_key: MY_SECRET_KEY
    regions: # You can specify multiple region if you need to
      - name: eu-central-1
        bucket_name: ephemer-{account_id}-{region_name}
      - name: eu-west-1
        bucket_name: ephemer-{account_id}-{region_name}
    # If the vpc does not exist, it will create it
    vpc_name: 'default'

redis:
  host: redis
  port: 6379

paw:
  host: paw
  port: 8901
